'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PriPROC6.Web.Feeds.Test.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[DATETOMIN]&apos;) AND type in (N&apos;FN&apos;, N&apos;IF&apos;, N&apos;TF&apos;, N&apos;FS&apos;, N&apos;FT&apos;))
        '''BEGIN
        '''execute dbo.sp_executesql @statement = N&apos;-- =============================================
        '''-- Author:		&lt;Author,,Name&gt;
        '''-- Create date: &lt;Create Date, ,&gt;
        '''-- Description:	&lt;Description, ,&gt;
        '''-- =============================================
        '''create FUNCTION [dbo].[DATETOMIN] 
        '''(
        '''	-- Add the parameters for the function here
        '''	@DT as datetime
        ''')
        '''RETURNS int
        '''AS
        '''BEGI [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property install() As String
            Get
                Return ResourceManager.GetString("install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to declare @part INT --mandatory
        '''
        '''select &apos;&apos;, (
        '''	select	PARTNAME
        '''	from PART
        '''	where PART in (@part)
        '''	for XML PATH(&apos;parts&apos;), type)
        '''for XML PATH(&apos;result&apos;), type.
        '''</summary>
        Friend ReadOnly Property query() As String
            Get
                Return ResourceManager.GetString("query", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
