Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: CUSTPERSONNEL as List(Of rowCUSTPERSONNEL)
''' Date: 13/11/2019
'''
''' </summary>
<oFormClass("rowCUSTPERSONNEL")>
Public Class CUSTPERSONNEL : Inherits oForm

    ''' <summary>
    ''' CUSTPERSONNEL Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the CUSTPERSONNEL form.
    ''' </summary>
    ''' <returns>rowCUSTPERSONNEL</returns>
    Public Function AddRow() As rowCUSTPERSONNEL
        With Me
            .Add(New rowCUSTPERSONNEL(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the CUSTPERSONNEL form.
''' </summary>
<oRowClass("CUSTPERSONNEL", "serialCUSTPERSONNEL")>
Public Class rowCUSTPERSONNEL : Inherits oRow

    ''' <summary>
    ''' rowCUSTPERSONNEL Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Name" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Name", Key:=True, length:=37)>
    Public Property NAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Name (Lang 2)" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Name (Lang 2)", length:=32)>
    Public Property ENAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "First Name" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("First Name", length:=16)>
    Public Property FIRSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Last Name" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Last Name", length:=20)>
    Public Property LASTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Initials" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Initials", length:=6)>
    Public Property INITIALS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Status" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Status", mandatory:=True, length:=20)>
    Public Property STATDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Inactive" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Inactive", ReadOnly:=True, length:=1)>
    Public Readonly Property INACTIVE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Assigned to" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Assigned to", length:=20)>
    Public Property OWNERLOGIN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Gender" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Gender", length:=1)>
    Public Property GENDER As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Phone Number" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Phone Number", length:=20)>
    Public Property PHONENUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Code (Position)" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Code (Position)", length:=4)>
    Public Property POSITIONCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Cell Phone" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cell Phone", length:=20)>
    Public Property CELLPHONE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Position" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Position", ReadOnly:=True, length:=32)>
    Public Readonly Property POSITIONDES2 As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Title" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Title", length:=5)>
    Public Property TITLEDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Office Phone" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Office Phone", length:=20)>
    Public Property OFFICEPHONE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Home Phone" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Home Phone", length:=20)>
    Public Property HOMEPHONE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Fax Number" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Fax Number", length:=20)>
    Public Property FAX As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "E-mail Address" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("E-mail Address", length:=48)>
    Public Property EMAIL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Consents to Rcv Mail" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Consents to Rcv Mail", length:=1)>
    Public Property MAILAPP As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Date Pass on Site" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date Pass on Site")>
    Public Property MED_WEBPASSDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Job Title" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Job Title", length:=32)>
    Public Property POSITIONDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales Rep Number" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Rep Number", length:=16)>
    Public Property AGENTCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Sales Rep Name" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Rep Name", ReadOnly:=True, length:=32)>
    Public Readonly Property AGENTNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Main Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Main Contact", length:=1)>
    Public Property MAINPHONE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Marketing Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Marketing Contact", length:=1)>
    Public Property DEALFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Price Quote Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Price Quote Contact", length:=1)>
    Public Property CPROFFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales Order Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Order Contact", length:=1)>
    Public Property ORDFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Shipment Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shipment Contact", length:=1)>
    Public Property DOCFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Invoice Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Invoice Contact", length:=1)>
    Public Property CIVFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Aging Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Aging Contact", length:=1)>
    Public Property TIVFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Cust Statemt Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust Statemt Contact", length:=1)>
    Public Property FNCFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Service Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Service Contact", length:=1)>
    Public Property SERVCALLFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Outgo Vouch Contact" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Outgo Vouch Contact", length:=1)>
    Public Property CONSINGEEFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Outgo Vouch Contact2" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Outgo Vouch Contact2", length:=1)>
    Public Property NOTIFYFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "eMerge SC allowed ?" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("eMerge SC allowed ?", length:=1)>
    Public Property EMG_SERVICE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Department" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Department", length:=16)>
    Public Property DEPARTMENT As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Profession" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Profession", length:=16)>
    Public Property PROFESSION As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Manager's Name" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Manager's Name", length:=24)>
    Public Property MANAGERNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Assistant's Name" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Assistant's Name", length:=24)>
    Public Property ASSISTANTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Assistant's Phone" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Assistant's Phone", length:=20)>
    Public Property ASSISTANTPHONE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Date of Birth" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date of Birth")>
    Public Property BIRTHDATE10 As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Site" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Site", length:=4)>
    Public Property DCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Site Description" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Site Description", ReadOnly:=True, length:=48)>
    Public Readonly Property CODEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Photograph" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Photograph", length:=66)>
    Public Property EXTFILENAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Send XMAS Card?" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Send XMAS Card?", length:=1)>
    Public Property ZEMG_XMAS_CARD As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "No Newletters?" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("No Newletters?", length:=1)>
    Public Property ZEMG_NONEWSLETTERS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Subs to newsletter?" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Subs to newsletter?", length:=1)>
    Public Property ZEMG_SUBSCRIBED As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Unsubs from newslett" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unsubs from newslett", length:=1)>
    Public Property ZEMG_UNSUBSCRIBED As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Medatech Libr. User?" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Medatech Libr. User?", length:=1)>
    Public Property ZEMG_MEDALIBRARYUSER As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Contact (ID)" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Contact (ID)")>
    Public Property PHONE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Company" Value of CUSTPERSONNEL.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Company", Key:=True, length:=48)>
    Public Property FIRM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowCUSTPERSONNEL.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialCUSTPERSONNEL 

    Public Property NAME As String
    Public Property ENAME As String
    Public Property FIRSTNAME As String
    Public Property LASTNAME As String
    Public Property INITIALS As String
    Public Property STATDES As String
    Public Property INACTIVE As String
    Public Property OWNERLOGIN As String
    Public Property GENDER As String
    Public Property PHONENUM As String
    Public Property POSITIONCODE As String
    Public Property CELLPHONE As String
    Public Property POSITIONDES2 As String
    Public Property TITLEDES As String
    Public Property OFFICEPHONE As String
    Public Property HOMEPHONE As String
    Public Property FAX As String
    Public Property EMAIL As String
    Public Property MAILAPP As String
    Public Property MED_WEBPASSDATE As Date?
    Public Property POSITIONDES As String
    Public Property AGENTCODE As String
    Public Property AGENTNAME As String
    Public Property MAINPHONE As String
    Public Property DEALFLAG As String
    Public Property CPROFFLAG As String
    Public Property ORDFLAG As String
    Public Property DOCFLAG As String
    Public Property CIVFLAG As String
    Public Property TIVFLAG As String
    Public Property FNCFLAG As String
    Public Property SERVCALLFLAG As String
    Public Property CONSINGEEFLAG As String
    Public Property NOTIFYFLAG As String
    Public Property EMG_SERVICE As String
    Public Property DEPARTMENT As String
    Public Property PROFESSION As String
    Public Property MANAGERNAME As String
    Public Property ASSISTANTNAME As String
    Public Property ASSISTANTPHONE As String
    Public Property BIRTHDATE10 As Date?
    Public Property DCODE As String
    Public Property CODEDES As String
    Public Property EXTFILENAME As String
    Public Property ZEMG_XMAS_CARD As String
    Public Property ZEMG_NONEWSLETTERS As String
    Public Property ZEMG_SUBSCRIBED As String
    Public Property ZEMG_UNSUBSCRIBED As String
    Public Property ZEMG_MEDALIBRARYUSER As String
    Public Property PHONE As Integer?
    Public Property FIRM As String


End Class