Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: ABILITIES as List(Of rowABILITIES)
''' Date: 06/05/2019
'''
''' </summary>
<oFormClass("rowABILITIES")>
Public Class ABILITIES : Inherits oForm

    ''' <summary>
    ''' ABILITIES Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the ABILITIES form.
    ''' </summary>
    ''' <returns>rowABILITIES</returns>
    Public Function AddRow() As rowABILITIES
        With Me
            .Add(New rowABILITIES(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the ABILITIES form.
''' </summary>
<oRowClass("ABILITIES", "serialABILITIES")>
Public Class rowABILITIES : Inherits oRow

    ''' <summary>
    ''' rowABILITIES Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Qualification Code" Value of ABILITIES.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Qualification Code", Key:=True, length:=3)>
    Public Property ABILITYCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Qualification Desc." Value of ABILITIES.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Qualification Desc.", length:=32)>
    Public Property ABILITYDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Qualification (ID)" Value of ABILITIES.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Qualification (ID)")>
    Public Property ABILITY As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowABILITIES.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialABILITIES 

    Public Property ABILITYCODE As String
    Public Property ABILITYDES As String
    Public Property ABILITY As Integer?


End Class