Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: CUSTOMERS as List(Of rowCUSTOMERS)
''' Date: 06/05/2019
'''
''' </summary>
<oFormClass("rowCUSTOMERS", "CUSTPERSONNEL")>
Public Class CUSTOMERS : Inherits oForm

    ''' <summary>
    ''' CUSTOMERS Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the CUSTOMERS form.
    ''' </summary>
    ''' <returns>rowCUSTOMERS</returns>
    Public Function AddRow() As rowCUSTOMERS
        With Me
            .Add(New rowCUSTOMERS(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the CUSTOMERS form.
''' </summary>
<oRowClass("CUSTOMERS", "serialCUSTOMERS")>
Public Class rowCUSTOMERS : Inherits oRow

    ''' <summary>
    ''' rowCUSTOMERS Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get/set the CUSTPERSONNEL subform.
    ''' </summary>
    ''' <returns>CUSTPERSONNEL</returns>
	Public Property CUSTPERSONNEL As CUSTPERSONNEL
        Get
            Return MyBase.SubForms("CUSTPERSONNEL")
        End Get
        Set(value As CUSTPERSONNEL)
            MyBase.SubForms("CUSTPERSONNEL") = value
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer Number" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Number", Key:=True, length:=16)>
    Public Property CUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer Name" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Name", mandatory:=True, length:=48)>
    Public Property CUSTDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Status" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Status", mandatory:=True, length:=12)>
    Public Property STATDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Assigned to" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Assigned to", mandatory:=True, length:=20)>
    Public Property OWNERLOGIN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Inactive" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Inactive", ReadOnly:=True, length:=1)>
    Public Readonly Property INACTIVEFLAG As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Date Opened" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date Opened")>
    Public Property CREATEDDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Status Update Date" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Status Update Date", ReadOnly:=True)>
    Public Readonly Property STATUSDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Phone Number" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Phone Number", length:=20)>
    Public Property PHONE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Fax Number" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Fax Number", length:=20)>
    Public Property FAX As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "E-mail Address" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("E-mail Address", length:=48)>
    Public Property EMAIL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Type of Business" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type of Business", length:=32)>
    Public Property BUSINESSTYPE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Representative Cust." Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Representative Cust.", length:=16)>
    Public Property MCUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Rep Customer Name" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Rep Customer Name", ReadOnly:=True, length:=48)>
    Public Readonly Property MCUSTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Cust. Group Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust. Group Code", length:=2)>
    Public Property CTYPECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Group Description" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Group Description", ReadOnly:=True, length:=32)>
    Public Readonly Property CTYPENAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Parent Company No." Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Parent Company No.", length:=16)>
    Public Property PCUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Secondary Group Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Secondary Group Code", length:=2)>
    Public Property CTYPE2CODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Parent Company Name" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Parent Company Name", ReadOnly:=True, length:=48)>
    Public Readonly Property PCUSTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Group Description" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Group Description", ReadOnly:=True, length:=32)>
    Public Readonly Property CTYPE2NAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Ship Cust Parts Only" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Ship Cust Parts Only", length:=1)>
    Public Property CUSTPART As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Change Name?" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Change Name?", length:=1)>
    Public Property NSFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Inactive" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Inactive", length:=1)>
    Public Property INACTIVE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Shipment Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shipment Code", length:=8)>
    Public Property STCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Shipping Method" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shipping Method", ReadOnly:=True, length:=48)>
    Public Readonly Property STDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Zone Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Zone Code", length:=2)>
    Public Property ZONECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Zone Description" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Zone Description", ReadOnly:=True, length:=10)>
    Public Readonly Property ZONEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Service Route" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Service Route", ReadOnly:=True, length:=2)>
    Public Readonly Property TRACK As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Street Address" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Street Address", length:=80)>
    Public Property ADDRESS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Address (Line 2)" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Address (Line 2)", length:=80)>
    Public Property ADDRESS2 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Address (Line 3)" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Address (Line 3)", length:=80)>
    Public Property ADDRESS3 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "City/State" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("City/State", length:=40)>
    Public Property STATE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "City" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("City", length:=40)>
    Public Property STATEA As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "State Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("State Code", length:=24)>
    Public Property STATECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "State" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("State", length:=40)>
    Public Property STATENAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Zip Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Zip Code", length:=10)>
    Public Property ZIP As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Country" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Country", length:=18)>
    Public Property COUNTRYNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Company Number" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Company Number", length:=10)>
    Public Property WTAXNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Type of Tax File" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type of Tax File", length:=1)>
    Public Property WTAXNUMEXPL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "VAT Number-Cust." Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("VAT Number-Cust.", length:=15)>
    Public Property VATNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales Rep Number" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Rep Number", length:=16)>
    Public Property AGENTCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Sales Rep Name" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Rep Name", ReadOnly:=True, length:=32)>
    Public Readonly Property AGENTNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Add'l Sales Rep No." Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Add'l Sales Rep No.", length:=16)>
    Public Property AGENTCODE2 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Add'l Sales Rep Name" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Add'l Sales Rep Name", ReadOnly:=True, length:=32)>
    Public Readonly Property AGENTNAME2 As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Territory Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Territory Code", length:=12)>
    Public Property TERRITORYCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Territory Name" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Territory Name", ReadOnly:=True, length:=32)>
    Public Readonly Property TERRITORYDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Rep's Commission (%)" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Rep's Commission (%)")>
    Public Property COMMISSION As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Year Established" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Year Established", length:=4)>
    Public Property ESTABLISHED As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Number of Employees" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Number of Employees")>
    Public Property EMPNUM As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Branch Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Branch Code", length:=6)>
    Public Property BRANCHNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Branch Name" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Branch Name", ReadOnly:=True, length:=32)>
    Public Readonly Property BRANCHDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Payment Terms Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Payment Terms Code", length:=3)>
    Public Property PAYCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Payment Terms" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Payment Terms", ReadOnly:=True, length:=24)>
    Public Readonly Property PAYDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Credit Limit" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Credit Limit")>
    Public Property MAX_CREDIT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Liability Limit" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Liability Limit")>
    Public Property MAX_OBLIGO As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Credit Currency" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Credit Currency", length:=3)>
    Public Property OBCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Distrib. Route Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Distrib. Route Code", length:=3)>
    Public Property DISTRLINECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Distrib. Route Desc." Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Distrib. Route Desc.", ReadOnly:=True, length:=12)>
    Public Readonly Property DISTRLINEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Unload Time (Deliv.)" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unload Time (Deliv.)", length:=6)>
    Public Property UNLOADTIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Delivery Order" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Delivery Order")>
    Public Property DISTRORDER As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Cust Forecasts Only" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust Forecasts Only", length:=1)>
    Public Property NOTALLOWFORECAST As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Gets Regular Bonus?" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Gets Regular Bonus?", length:=1)>
    Public Property BONUSFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Competitor?" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Competitor?", length:=1)>
    Public Property COMPETITORFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales/Order Target?" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales/Order Target?", length:=1)>
    Public Property FORECAST As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales Channel?" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Channel?", length:=1)>
    Public Property CHANEL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Distribution Type" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Distribution Type", length:=3)>
    Public Property DISTRTYPECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Distrib. Type Desc." Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Distrib. Type Desc.", ReadOnly:=True, length:=32)>
    Public Readonly Property DISTRTYPEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Printouts in Lang 2?" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Printouts in Lang 2?", length:=1)>
    Public Property SECONDLANGTEXT As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Secured Customer?" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Secured Customer?", length:=1)>
    Public Property CONFIDENTIAL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Web Site" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Web Site", length:=48)>
    Public Property HOSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC1.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC1.F}", length:=32)>
    Public Property SPEC1 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC2.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC2.F}", length:=32)>
    Public Property SPEC2 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC3.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC3.F}", length:=32)>
    Public Property SPEC3 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC4.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC4.F}", length:=32)>
    Public Property SPEC4 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC5.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC5.F}", length:=32)>
    Public Property SPEC5 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC6.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC6.F}", length:=32)>
    Public Property SPEC6 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC7.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC7.F}", length:=32)>
    Public Property SPEC7 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC8.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC8.F}", length:=32)>
    Public Property SPEC8 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC9.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC9.F}", length:=32)>
    Public Property SPEC9 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC10.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC10.F}", length:=32)>
    Public Property SPEC10 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC11.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC11.F}", length:=32)>
    Public Property SPEC11 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC12.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC12.F}", length:=32)>
    Public Property SPEC12 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC13.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC13.F}", length:=32)>
    Public Property SPEC13 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC14.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC14.F}", length:=32)>
    Public Property SPEC14 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC15.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC15.F}", length:=32)>
    Public Property SPEC15 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC16.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC16.F}", length:=32)>
    Public Property SPEC16 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC17.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC17.F}", length:=32)>
    Public Property SPEC17 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC18.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC18.F}", length:=32)>
    Public Property SPEC18 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC19.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC19.F}", length:=32)>
    Public Property SPEC19 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{CUSTSPEC_SPEC20.F}" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{CUSTSPEC_SPEC20.F}", length:=32)>
    Public Property SPEC20 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Attachments?" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Attachments?", ReadOnly:=True, length:=1)>
    Public Readonly Property EXTFILEFLAG As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Task Split Method" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Task Split Method", length:=3)>
    Public Property WAVESTRATEGYCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Splitting Method" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Splitting Method", ReadOnly:=True, length:=32)>
    Public Readonly Property WAVESTRATEGYDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Pick Strategy Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Pick Strategy Code", length:=3)>
    Public Property PICKSTGCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Strategy Description" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Strategy Description", ReadOnly:=True, length:=24)>
    Public Readonly Property PICKSTGDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "AutoShip Pack Crates" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("AutoShip Pack Crates", length:=1)>
    Public Property AUTOSHPFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Latitude" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Latitude", length:=20)>
    Public Property GPSX As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Longitude" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Longitude", length:=20)>
    Public Property GPSY As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Quality Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Quality Code", length:=4)>
    Public Property QRANKCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Quality Description" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Quality Description", ReadOnly:=True, length:=32)>
    Public Readonly Property QRANKDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Allowed Inv Age-Mos." Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Allowed Inv Age-Mos.")>
    Public Property DCMONTHS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Billing Currency" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Billing Currency", mandatory:=True, length:=3)>
    Public Property CODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Tax Code" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Tax Code", mandatory:=True, length:=8)>
    Public Property TAXCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Tax Description" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Tax Description", ReadOnly:=True, length:=56)>
    Public Readonly Property TAXDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Cust's Instructions" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust's Instructions", length:=48)>
    Public Property CUSTREMARK As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Pick Order" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Pick Order")>
    Public Property PIKORDER As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Days Until Expirat'n" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Days Until Expirat'n")>
    Public Property MINEXPDAYS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer (ID)" Value of CUSTOMERS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Customer (ID)")>
    Public Property CUST As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowCUSTOMERS.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialCUSTOMERS 

    Public Property CUSTNAME As String
    Public Property CUSTDES As String
    Public Property STATDES As String
    Public Property OWNERLOGIN As String
    Public Property INACTIVEFLAG As String
    Public Property CREATEDDATE As Date?
    Public Property STATUSDATE As Date?
    Public Property PHONE As String
    Public Property FAX As String
    Public Property EMAIL As String
    Public Property BUSINESSTYPE As String
    Public Property MCUSTNAME As String
    Public Property MCUSTDES As String
    Public Property CTYPECODE As String
    Public Property CTYPENAME As String
    Public Property PCUSTNAME As String
    Public Property CTYPE2CODE As String
    Public Property PCUSTDES As String
    Public Property CTYPE2NAME As String
    Public Property CUSTPART As String
    Public Property NSFLAG As String
    Public Property INACTIVE As String
    Public Property STCODE As String
    Public Property STDES As String
    Public Property ZONECODE As String
    Public Property ZONEDES As String
    Public Property TRACK As String
    Public Property ADDRESS As String
    Public Property ADDRESS2 As String
    Public Property ADDRESS3 As String
    Public Property STATE As String
    Public Property STATEA As String
    Public Property STATECODE As String
    Public Property STATENAME As String
    Public Property ZIP As String
    Public Property COUNTRYNAME As String
    Public Property WTAXNUM As String
    Public Property WTAXNUMEXPL As String
    Public Property VATNUM As String
    Public Property AGENTCODE As String
    Public Property AGENTNAME As String
    Public Property AGENTCODE2 As String
    Public Property AGENTNAME2 As String
    Public Property TERRITORYCODE As String
    Public Property TERRITORYDES As String
    Public Property COMMISSION As Decimal?
    Public Property ESTABLISHED As String
    Public Property EMPNUM As Integer?
    Public Property BRANCHNAME As String
    Public Property BRANCHDES As String
    Public Property PAYCODE As String
    Public Property PAYDES As String
    Public Property MAX_CREDIT As Decimal?
    Public Property MAX_OBLIGO As Decimal?
    Public Property OBCODE As String
    Public Property DISTRLINECODE As String
    Public Property DISTRLINEDES As String
    Public Property UNLOADTIME As String
    Public Property DISTRORDER As Integer?
    Public Property NOTALLOWFORECAST As String
    Public Property BONUSFLAG As String
    Public Property COMPETITORFLAG As String
    Public Property FORECAST As String
    Public Property CHANEL As String
    Public Property DISTRTYPECODE As String
    Public Property DISTRTYPEDES As String
    Public Property SECONDLANGTEXT As String
    Public Property CONFIDENTIAL As String
    Public Property HOSTNAME As String
    Public Property SPEC1 As String
    Public Property SPEC2 As String
    Public Property SPEC3 As String
    Public Property SPEC4 As String
    Public Property SPEC5 As String
    Public Property SPEC6 As String
    Public Property SPEC7 As String
    Public Property SPEC8 As String
    Public Property SPEC9 As String
    Public Property SPEC10 As String
    Public Property SPEC11 As String
    Public Property SPEC12 As String
    Public Property SPEC13 As String
    Public Property SPEC14 As String
    Public Property SPEC15 As String
    Public Property SPEC16 As String
    Public Property SPEC17 As String
    Public Property SPEC18 As String
    Public Property SPEC19 As String
    Public Property SPEC20 As String
    Public Property EXTFILEFLAG As String
    Public Property WAVESTRATEGYCODE As String
    Public Property WAVESTRATEGYDES As String
    Public Property PICKSTGCODE As String
    Public Property PICKSTGDES As String
    Public Property AUTOSHPFLAG As String
    Public Property GPSX As String
    Public Property GPSY As String
    Public Property QRANKCODE As String
    Public Property QRANKDES As String
    Public Property DCMONTHS As Integer?
    Public Property CODE As String
    Public Property TAXCODE As String
    Public Property TAXDES As String
    Public Property CUSTREMARK As String
    Public Property PIKORDER As Integer?
    Public Property MINEXPDAYS As Integer?
    Public Property CUST As Integer?


End Class