Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: FAMILY_LOG as List(Of rowFAMILY_LOG)
''' Date: 06/05/2019
'''
''' </summary>
<oFormClass("rowFAMILY_LOG")>
Public Class FAMILY_LOG : Inherits oForm

    ''' <summary>
    ''' FAMILY_LOG Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the FAMILY_LOG form.
    ''' </summary>
    ''' <returns>rowFAMILY_LOG</returns>
    Public Function AddRow() As rowFAMILY_LOG
        With Me
            .Add(New rowFAMILY_LOG(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the FAMILY_LOG form.
''' </summary>
<oRowClass("FAMILY_LOG", "serialFAMILY_LOG")>
Public Class rowFAMILY_LOG : Inherits oRow

    ''' <summary>
    ''' rowFAMILY_LOG Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Family" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family", Key:=True, mandatory:=True, length:=8)>
    Public Property FAMILYNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Family Description" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family Description", length:=32)>
    Public Property FAMILYDESC As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Family Desc (Lang 2)" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family Desc (Lang 2)", length:=32)>
    Public Property EFAMILYDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Work Hours?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Hours?", length:=1)>
    Public Property TECHFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bill Project Report?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bill Project Report?", length:=1)>
    Public Property DEBITFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Production for Proj?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Production for Proj?", length:=1)>
    Public Property PROJPROCESS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Technician in Charge" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Technician in Charge", length:=20)>
    Public Property TECHNICIANLOGIN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Family Type Code" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family Type Code", length:=4)>
    Public Property FTCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Family Type Descrip." Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family Type Descrip.", ReadOnly:=True, length:=20)>
    Public Readonly Property FTNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Delivery Scheduling?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Delivery Scheduling?", length:=1)>
    Public Property DISTRFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Air Cost (%)" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Air Cost (%)")>
    Public Property DUTYPERCENT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sea Cost (%)" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Sea Cost (%)")>
    Public Property DUTYPERCENT1 As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Land Cost (%)" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Land Cost (%)")>
    Public Property DUTYPERCENT2 As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Shipping Cost Type" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shipping Cost Type", length:=1)>
    Public Property DUTYPERCENTTYPE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sold Part?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sold Part?", length:=1)>
    Public Property SELLFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Block Neg. Balance?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Block Neg. Balance?", length:=1)>
    Public Property NEGBALFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales/Order Target?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales/Order Target?", length:=1)>
    Public Property FORECAST As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sample Part" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sample Part", length:=22)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Part Description" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", ReadOnly:=True, length:=48)>
    Public Readonly Property PARTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Put Strategy Code" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Put Strategy Code", length:=8)>
    Public Property STORAGETYPECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Put Strategy Descrip" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Put Strategy Descrip", ReadOnly:=True, length:=32)>
    Public Readonly Property STORAGETYPEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Monthly Expir-Pick" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Monthly Expir-Pick", length:=1)>
    Public Property SERIALMONTHEXPIRY As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Top-Level?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Top-Level?", length:=1)>
    Public Property ISMFAMILY As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Top-Level Family" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Top-Level Family", length:=8)>
    Public Property MFAMILYNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Family Description" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family Description", ReadOnly:=True, length:=32)>
    Public Readonly Property MFAMILYDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Not in Use" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Not in Use", length:=1)>
    Public Property INACTIVE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Meter?" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Meter?", length:=1)>
    Public Property METERFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Family (ID)" Value of FAMILY_LOG.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Family (ID)")>
    Public Property FAMILY As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowFAMILY_LOG.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialFAMILY_LOG 

    Public Property FAMILYNAME As String
    Public Property FAMILYDESC As String
    Public Property EFAMILYDES As String
    Public Property TECHFLAG As String
    Public Property DEBITFLAG As String
    Public Property PROJPROCESS As String
    Public Property TECHNICIANLOGIN As String
    Public Property FTCODE As String
    Public Property FTNAME As String
    Public Property DISTRFLAG As String
    Public Property DUTYPERCENT As Decimal?
    Public Property DUTYPERCENT1 As Decimal?
    Public Property DUTYPERCENT2 As Decimal?
    Public Property DUTYPERCENTTYPE As String
    Public Property SELLFLAG As String
    Public Property NEGBALFLAG As String
    Public Property FORECAST As String
    Public Property PARTNAME As String
    Public Property PARTDES As String
    Public Property STORAGETYPECODE As String
    Public Property STORAGETYPEDES As String
    Public Property SERIALMONTHEXPIRY As String
    Public Property ISMFAMILY As String
    Public Property MFAMILYNAME As String
    Public Property MFAMILYDES As String
    Public Property INACTIVE As String
    Public Property METERFLAG As String
    Public Property FAMILY As Integer?


End Class