'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8937
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization
Public Enum eAddressType
    Delivery
    Billing
End Enum
'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class request

    Private customerField As requestCustomer

    '''<remarks/>
    Public Property customer() As requestCustomer
        Get
            Return Me.customerField
        End Get
        Set
            Me.customerField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class requestCustomer

    Private contactField As requestCustomerContact

    Private addressField() As requestCustomerAddress

    Private orderField As requestCustomerOrder

    Private nameField As String

    Private descField As String

    '''<remarks/>
    Public Property contact() As requestCustomerContact
        Get
            Return Me.contactField
        End Get
        Set
            Me.contactField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("address")>
    Public Property address() As requestCustomerAddress()
        Get
            Return Me.addressField
        End Get
        Set
            Me.addressField = Value
        End Set
    End Property

    Public ReadOnly Property address(AddressType As eAddressType) As requestCustomerAddress
        Get
            For Each a As requestCustomerAddress In Me.addressField
                If a.type.Substring(0, 1).ToLower = "b" And AddressType = eAddressType.Billing Then
                    Return a

                ElseIf a.type.Substring(0, 1).ToLower = "d" And AddressType = eAddressType.Delivery Then
                    Return a

                End If
            Next
            Return Nothing
        End Get

    End Property

    '''<remarks/>
    Public Property order() As requestCustomerOrder
        Get
            Return Me.orderField
        End Get
        Set
            Me.orderField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property desc() As String
        Get
            Return Me.descField
        End Get
        Set
            Me.descField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class requestCustomerContact

    Private nameField As String

    Private emailField As String

    Private phoneField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property email() As String
        Get
            Return Me.emailField
        End Get
        Set
            Me.emailField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property phone() As String
        Get
            Return Me.phoneField
        End Get
        Set
            Me.phoneField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class requestCustomerAddress

    Private address1Field As String

    Private address2Field As String

    Private address3Field As String

    Private cityField As String

    Private countyField As String

    Private postcodeField As String

    Private countryField As String

    Private typeField As String

    '''<remarks/>
    Public Property address1() As String
        Get
            Return Me.address1Field
        End Get
        Set
            Me.address1Field = Value
        End Set
    End Property

    '''<remarks/>
    Public Property address2() As String
        Get
            Return Me.address2Field
        End Get
        Set
            Me.address2Field = Value
        End Set
    End Property

    '''<remarks/>
    Public Property address3() As String
        Get
            Return Me.address3Field
        End Get
        Set
            Me.address3Field = Value
        End Set
    End Property

    '''<remarks/>
    Public Property city() As String
        Get
            Return Me.cityField
        End Get
        Set
            Me.cityField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property county() As String
        Get
            Return Me.countyField
        End Get
        Set
            Me.countyField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property postcode() As String
        Get
            Return Me.postcodeField
        End Get
        Set
            Me.postcodeField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property country() As String
        Get
            Return Me.countryField
        End Get
        Set
            Me.countryField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class requestCustomerOrder

    Private itemField() As requestCustomerOrderItem

    Private paymentField As requestCustomerOrderPayment

    Private orderrefField As String

    Private _PriorityOrdName As String

    Public Property PriorityOrdName As String
        Get
            Return _PriorityOrdName
        End Get
        Set(value As String)
            _PriorityOrdName = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("item")>
    Public Property item() As requestCustomerOrderItem()
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property payment() As requestCustomerOrderPayment
        Get
            Return Me.paymentField
        End Get
        Set
            Me.paymentField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property orderref() As String
        Get
            Return Me.orderrefField
        End Get
        Set
            Me.orderrefField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class requestCustomerOrderItem

    Private propertyField() As requestCustomerOrderItemProperty

    Private nameField As String

    Private qtyField As String

    Private dueField As Date

    Private priceField As Decimal

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("property")>
    Public Property [property]() As requestCustomerOrderItemProperty()
        Get
            Return Me.propertyField
        End Get
        Set
            Me.propertyField = Value
        End Set
    End Property

    Public ReadOnly Property [property](name As String) As String
        Get
            For Each prop As requestCustomerOrderItemProperty In propertyField
                If String.Compare(name, prop.name, True) = 0 Then
                    Return prop.value
                End If
            Next
            Return ""
        End Get
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>
    Public Property qty() As String
        Get
            Return Me.qtyField
        End Get
        Set
            Me.qtyField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property due() As Date
        Get
            Return Me.dueField
        End Get
        Set
            Me.dueField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property price() As Decimal
        Get
            Return Me.priceField
        End Get
        Set
            Me.priceField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class requestCustomerOrderItemProperty

    Private nameField As String

    Private valueField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class requestCustomerOrderPayment

    Private providerField As String

    Private referenceField As String

    Private valueField As Decimal

    Private currencyField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property provider() As String
        Get
            Return Me.providerField
        End Get
        Set
            Me.providerField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property reference() As String
        Get
            Return Me.referenceField
        End Get
        Set
            Me.referenceField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property value() As Decimal
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property currency() As String
        Get
            Return Me.currencyField
        End Get
        Set
            Me.currencyField = Value
        End Set
    End Property
End Class
